_format_version: "1.1"
_workspace: default
consumers:
- keyauth_credentials:
  - key: secret
  username: consumer-service-1
services:
- connect_timeout: 60000
  host: 172.24.144.1
  name: GraphQL-service
  path: /graphql
  plugins:
  - config:
      cost_strategy: default
      dictionary_name: kong_rate_limiting_counters
      hide_client_headers: false
      identifier: consumer
      limit:
      - 5
      max_cost: 0
      namespace: vF06y090RQcDLBxdoTu8zGfJwcsfyKZD
      redis:
        cluster_addresses: null
        connect_timeout: null
        database: 0
        host: null
        keepalive_backlog: null
        keepalive_pool_size: 30
        password: null
        port: null
        read_timeout: null
        send_timeout: null
        sentinel_addresses: null
        sentinel_master: null
        sentinel_password: null
        sentinel_role: null
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
      score_factor: 1
      strategy: cluster
      sync_rate: -1
      window_size:
      - 30
      window_type: sliding
    enabled: true
    name: graphql-rate-limiting-advanced
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 4000
  protocol: http
  read_timeout: 60000
  retries: 30
  routes:
  - https_redirect_status_code: 426
    name: graphql-route
    path_handling: v0
    paths:
    - /graphql
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  host: httpbin.org
  name: service-1
  path: /get
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: route-1
    path_handling: v0
    paths:
    - /service-1
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  host: httpbin.org
  name: service-2
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: route-2
    path_handling: v0
    paths:
    - /service-2
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  host: httpbin.org
  name: service-3
  path: /get
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: route-3
    path_handling: v0
    paths:
    - /service-3
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
